version: "3.8"

services:
  django:
    image: byeongyeongtae/pbl2-django:latest
    container_name: pbl2-django
    restart: always
    networks:
      - mojadol-network
    ports:
      - "4401:4401"
    volumes:
      - /home/bgt/pbl2/model:/home/bgt/pbl2/model


networks:
  mojadol-network:
    external: true